openapi: 3.0.3
info:
  title: Gacha Management System API Documentation
  version: 1.0.0
  description: |
    Admin API for managing gacha, prizes, admin and operational analytics. This spec is designed
    for contract-first development and works well with Postman docs + mock servers.
  contact:
    name: API Support
    email: sokritha@marinax.co.jp
servers:
  - url: /api/v1
    description: API base path
tags:
  - name: Dashboard
  - name: Gacha
  - name: Prizes
  - name: Auth
  - name: User
  - name: Logs
  - name: Admins
components:
  securitySchemes:
    $ref: './components/security.yaml'
  headers:
    $ref: './components/headers.yaml'
  schemas:
    $ref: './components/schemas.yaml'
security:
  - SessionAuth: []
paths:
  $ref: './paths/paths.yaml'